// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GrpcGatewayPracticeServiceClient is the client API for GrpcGatewayPracticeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrpcGatewayPracticeServiceClient interface {
}

type grpcGatewayPracticeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrpcGatewayPracticeServiceClient(cc grpc.ClientConnInterface) GrpcGatewayPracticeServiceClient {
	return &grpcGatewayPracticeServiceClient{cc}
}

// GrpcGatewayPracticeServiceServer is the server API for GrpcGatewayPracticeService service.
// All implementations should embed UnimplementedGrpcGatewayPracticeServiceServer
// for forward compatibility
type GrpcGatewayPracticeServiceServer interface {
}

// UnimplementedGrpcGatewayPracticeServiceServer should be embedded to have forward compatible implementations.
type UnimplementedGrpcGatewayPracticeServiceServer struct {
}

// UnsafeGrpcGatewayPracticeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrpcGatewayPracticeServiceServer will
// result in compilation errors.
type UnsafeGrpcGatewayPracticeServiceServer interface {
	mustEmbedUnimplementedGrpcGatewayPracticeServiceServer()
}

func RegisterGrpcGatewayPracticeServiceServer(s grpc.ServiceRegistrar, srv GrpcGatewayPracticeServiceServer) {
	s.RegisterService(&GrpcGatewayPracticeService_ServiceDesc, srv)
}

// GrpcGatewayPracticeService_ServiceDesc is the grpc.ServiceDesc for GrpcGatewayPracticeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrpcGatewayPracticeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_gateway_practice.v1.GrpcGatewayPracticeService",
	HandlerType: (*GrpcGatewayPracticeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "grpc_gateway_practice/v1/api.proto",
}
